[package]
name = "secrets_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.4.0"
serde = "1.0.188"
sqlx = { version = "0.7.1", features = ["mysql", "chrono"] }
