version: "3.7"
services:
  db:
    image: mariadb:11.1.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
